PACKAGE:
  NAME: light_side
  ARCH: archs
  MODEL: models

MODEL:
  zerodce:
    3-32-16:
      zerodce:
        v0:
          url: "https://github.com/canturan10/light_side/releases/download/v0.0.1/zerodce_3-32-16_zerodce.pth"
          onnx: "https://github.com/canturan10/light_side/releases/download/v0.0.1/zerodce_3-32-16_zerodce.onnx"
          quantize-onnx: "https://github.com/canturan10/light_side/releases/download/v0.0.1/zerodce_3-32-16_zerodce_quantize.onnx"
        v1:
          url: "https://github.com/canturan10/light_side/releases/download/v0.0.2/zerodce_3-32-16_zerodce.pth"
          onnx: "https://github.com/canturan10/light_side/releases/download/v0.0.2/zerodce_3-32-16_zerodce.onnx"
          quantize-onnx: "https://github.com/canturan10/light_side/releases/download/v0.0.2/zerodce_3-32-16_zerodce_quantize.onnx"
      private:
        v0:
          url: ""
        v1:
          url: ""
    7-16-8:
      zerodce:
        v0:
          url: "https://github.com/canturan10/light_side/releases/download/v0.0.1/zerodce_7-16-8_zerodce.pth"
          onnx: "https://github.com/canturan10/light_side/releases/download/v0.0.1/zerodce_7-16-8_zerodce.onnx"
          quantize-onnx: "https://github.com/canturan10/light_side/releases/download/v0.0.1/zerodce_7-16-8_zerodce_quantize.onnx"
        v1:
          url: "https://github.com/canturan10/light_side/releases/download/v0.0.2/zerodce_7-16-8_zerodce.pth"
          onnx: "https://github.com/canturan10/light_side/releases/download/v0.0.2/zerodce_7-16-8_zerodce.onnx"
          quantize-onnx: "https://github.com/canturan10/light_side/releases/download/v0.0.2/zerodce_7-16-8_zerodce_quantize.onnx"
      private:
        v0:
          url: ""
        v1:
          url: ""
    7-32-8:
      zerodce:
        v0:
          url: "https://github.com/canturan10/light_side/releases/download/v0.0.1/zerodce_7-32-8_zerodce.pth"
          onnx: "https://github.com/canturan10/light_side/releases/download/v0.0.1/zerodce_7-32-8_zerodce.onnx"
          quantize-onnx: "https://github.com/canturan10/light_side/releases/download/v0.0.1/zerodce_7-32-8_zerodce_quantize.onnx"
        v1:
          url: "https://github.com/canturan10/light_side/releases/download/v0.0.2/zerodce_7-32-8_zerodce.pth"
          onnx: "https://github.com/canturan10/light_side/releases/download/v0.0.2/zerodce_7-32-8_zerodce.onnx"
          quantize-onnx: "https://github.com/canturan10/light_side/releases/download/v0.0.2/zerodce_7-32-8_zerodce_quantize.onnx"
      private:
        v0:
          url: ""
        v1:
          url: ""
    7-32-16:
      zerodce:
        v0:
          url: "https://github.com/canturan10/light_side/releases/download/v0.0.1/zerodce_7-32-16_zerodce.pth"
          onnx: "https://github.com/canturan10/light_side/releases/download/v0.0.1/zerodce_7-32-16_zerodce.onnx"
          quantize-onnx: "https://github.com/canturan10/light_side/releases/download/v0.0.1/zerodce_7-32-16_zerodce_quantize.onnx"
        v1:
          url: "https://github.com/canturan10/light_side/releases/download/v0.0.2/zerodce_7-32-16_zerodce.pth"
          onnx: "https://github.com/canturan10/light_side/releases/download/v0.0.2/zerodce_7-32-16_zerodce.onnx"
          quantize-onnx: "https://github.com/canturan10/light_side/releases/download/v0.0.2/zerodce_7-32-16_zerodce_quantize.onnx"
      private:
        v0:
          url: ""
        v1:
          url: ""
