PACKAGE:
  NAME: light_side
  ARCH: archs
  MODEL: models

MODEL:
  zerodce:
    3-32-16:
      zerodce:
        v0:
          url: ""
    7-16-8:
      zerodce:
        v0:
          url: ""
    7-32-1:
      zerodce:
        v0:
          url: ""
    7-32-8:
      zerodce:
        v0:
          url: ""
    7-32-16:
      zerodce:
        v0:
          url: ""
